# Generated by Django 6.0.7 on 2026-10-01 02:55

import django.db.models.functions.text
from django.db import migrations, models


def stop_if_emails_are_repeated(apps, schema_editor):
    # Si la base ya tiene correos repetidos, la regla no se puede crear.
    # En vez del error tecnico de la base de datos, se explica cuales son
    # para que se corrijan (por ejemplo desde /admin/) antes de migrar.
    User = apps.get_model("accounts", "User")
    repeated = (
        User.objects.exclude(email="")
        .annotate(normalized=django.db.models.functions.text.Lower("email"))
        .values("normalized")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
        .values_list("normalized", flat=True)
    )
    if repeated:
        raise RuntimeError(
            "Cannot add the unique email rule: these emails are used by more "
            "than one account: " + ", ".join(sorted(repeated)) + ". "
            "Change or delete the extra accounts and run migrate again."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_status_changed_at_user_status_changed_by'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(stop_if_emails_are_repeated, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='unique_user_email_case_insensitive'),
        ),
    ]
