# Generated by Django 6.0.7 on 2026-08-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_itemreport_moderated_at_itemreport_moderated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreport',
            name='recovered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
